import type { RoleId } from "../../config/roleConfig";

export type EmploymentStatusTab = "preboarding" | "current" | "past";

export type EmployeeListRow = {
  id: string;
  email: string;
  name: string | null;
  role: RoleId;
  employmentStatus: EmploymentStatusTab;
  employeeCode: string;
  phone: string;
  dateOfJoining: string;
  dateOfLeaving?: string;
  ctc?: number | null;
  createdAt: string;
  designation?: string | null;
  departmentName?: string | null;
  divisionName?: string | null;
  shiftName?: string | null;
  preboardingDocsComplete?: boolean;
};

export type EmployeeDetail = {
  id: string;
  email: string;
  name: string;
  role: RoleId;
  employmentStatus: EmploymentStatusTab;
  employeeCode: string;
  phone: string;
  dateOfBirth: string;
  dateOfJoining: string;
  gender: string;
  designation: string;
  designationId: string;
  departmentId: string;
  divisionId: string;
  shiftId: string;
  aadhaar: string;
  pan: string;
  uanNumber: string;
  pfNumber: string;
  esicNumber: string;
  governmentPayLevel: number | null;
  grossBasic: number | null;
  cpfNumber: string;
  currentAddressLine1: string;
  currentAddressLine2: string;
  currentCity: string;
  currentState: string;
  currentCountry: string;
  currentPostalCode: string;
  permanentAddressLine1: string;
  permanentAddressLine2: string;
  permanentCity: string;
  permanentState: string;
  permanentCountry: string;
  permanentPostalCode: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  bankName: string;
  bankAccountNumber: string;
  bankIfsc: string;
  grossSalary: number | null;
  incomeTaxMonthly: number;
  tds: number;
  pfEligible: boolean;
  esicEligible: boolean;
};
