import test from "node:test";
import assert from "node:assert/strict";
import { computeEsicEmployer, defaultSalaryBreakup, isLegacyAutoGeneratedSeptemberBreakup } from "./payrollCalc";
import { DEFAULT_PRIVATE_PAYROLL_CONFIG } from "./payrollConfig";
import { applicablePrivatePayrollPolicy } from "./privatePayrollPolicy";

const expected = [
  [37595, 18798, 7519, 1566, 9712], [36995, 18498, 7399, 1541, 9557],
  [113281, 56641, 22656, 4718, 29266], [110000, 55000, 22000, 4582, 28418],
  [22200, 14290, 0, 1190, 6720], [27910, 14290, 0, 1190, 12430],
  [68133, 34067, 13627, 2838, 17601], [27500, 14290, 0, 1190, 12020],
  [37783, 18892, 7557, 1574, 9760], [60000, 30000, 12000, 2499, 15501],
  [10000, 10000, 0, 0, 0], [15000, 15000, 0, 0, 0],
];

test("September 2026 private breakup matches supplied salary structure", () => {
  const september = { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, roundMasterComponents: true };
  for (const [gross, basic, hra, bonus, special] of expected) {
    const got = defaultSalaryBreakup(gross, september);
    assert.deepEqual([got.basic, got.hra, got.medical, got.personal], [basic, hra, bonus, special]);
    assert.equal(got.basic + got.hra + got.medical + got.personal, gross);
  }
});

test("all Payroll Master auto-breakups use whole rupees", () => {
  const got = defaultSalaryBreakup(37784, DEFAULT_PRIVATE_PAYROLL_CONFIG);
  assert.deepEqual(got, { basic: 18892, hra: 7557, medical: 1574, trans: 0, lta: 0, personal: 9761 });
  assert.equal(got.basic + got.hra + got.medical + got.personal, 37784);
});

test("Gourav master regression rounds before calculating special allowance", () => {
  const got = defaultSalaryBreakup(37595, { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, roundMasterComponents: true });
  assert.deepEqual(got, { basic: 18798, hra: 7519, medical: 1566, trans: 0, lta: 0, personal: 9712 });
});

test("September employer ESIC follows the rounded employee ESIC Excel formula", () => {
  const september = { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, esicEmployerFromEmployeeEsic: true };
  // CEIL(18,892 × 0.75%) = 142; 142 / 0.75% × 3.25% = 615.33 → 615.
  assert.equal(computeEsicEmployer(18892, true, september), 615);
  assert.equal(37783 + 2456 + computeEsicEmployer(18892, true, september), 40854);
});

test("existing decimal September auto-master is normalized, while manual overrides are preserved", () => {
  const september = { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, roundMasterComponents: true };
  const oldAuto = { basic: 18798, hra: 7519.2, medical: 1566, trans: 0, lta: 0, personal: 9711.8 };
  assert.equal(isLegacyAutoGeneratedSeptemberBreakup(37595, oldAuto, september), true);
  assert.deepEqual(defaultSalaryBreakup(37595, september), {
    basic: 18798, hra: 7519, medical: 1566, trans: 0, lta: 0, personal: 9712,
  });
  assert.equal(
    isLegacyAutoGeneratedSeptemberBreakup(37595, { ...oldAuto, hra: 7500, personal: 9731 }, september),
    false,
  );
});

test("policy selection is date effective and leaves the legacy formula available", () => {
  const legacy = { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, basicDaFloorWhenHalfGrossLow: 0 };
  const september = { ...DEFAULT_PRIVATE_PAYROLL_CONFIG, basicDaFloorWhenHalfGrossLow: 14290 };
  assert.equal(applicablePrivatePayrollPolicy("2026-08-31", [{ effective_from: "2026-09-01", private_config: september }], legacy).basicDaFloorWhenHalfGrossLow, 0);
  assert.equal(applicablePrivatePayrollPolicy("2026-09-01", [{ effective_from: "2026-09-01", private_config: september }], legacy).basicDaFloorWhenHalfGrossLow, 14290);
});
